# Traffic Flow Forecast Analysis - EDA & Data Wrangling

Author: Nick Peril  
Project: Personal Portfolio   
Dataset: [Traffic Flow Forecasting (UCI Repository)](https://archive.ics.uci.edu/dataset/608/traffic+flow+forecasting)

## Objective
To forecast the spatio-temporal traffic volume based on the historical traffic volume and other features in neighboring locations.
To predict a feature..

### Importing libraries:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import loadmat

### Loading my dataset using scipy:

In [2]:
data = loadmat('/Users/saadult/traffic-flow-analysis/data/traffic_dataset_raw.mat')
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'tra_X_tr', 'tra_X_te', 'tra_Y_tr', 'tra_Y_te', 'tra_adj_mat'])

### Inspecting my dataset structure:

In [3]:
traffic = data['tra_X_tr'][0][0]
traffic.shape

(36, 48)

In [4]:
data['tra_X_tr']

array([[<Compressed Sparse Column sparse array of dtype 'float64'
        	with 540 stored elements and shape (36, 48)>            ,
        <Compressed Sparse Column sparse array of dtype 'float64'
        	with 540 stored elements and shape (36, 48)>            ,
        <Compressed Sparse Column sparse array of dtype 'float64'
        	with 540 stored elements and shape (36, 48)>            , ...,
        <Compressed Sparse Column sparse array of dtype 'float64'
        	with 540 stored elements and shape (36, 48)>            ,
        <Compressed Sparse Column sparse array of dtype 'float64'
        	with 540 stored elements and shape (36, 48)>            ,
        <Compressed Sparse Column sparse array of dtype 'float64'
        	with 540 stored elements and shape (36, 48)>            ]],
      shape=(1, 1261), dtype=object)

In [5]:
type(data['tra_X_tr'])

numpy.ndarray

In [6]:
data['tra_X_tr'].shape

(1, 1261)

In [7]:
traffic = data['tra_X_tr'][0]
len(traffic)

1261

##### ***This dataset is 3-dimensional. It is very typical for spatio-temporal traffic data. I need to convert this dataset into a useable format.***

In [8]:
traffic_array = np.stack([t.toarray() for t in traffic])
traffic_array.shape

(1261, 36, 48)

### Flattening the data so i can make it easier to analyze:

In [9]:
X = traffic_array.reshape(1261, -1)
X.shape

(1261, 1728)

In [10]:
df = pd.DataFrame(X)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727
0,0.092480,0.096684,0.070061,0.065857,0.078468,0.071462,0.054180,0.044372,0.054647,0.050911,...,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.096684,0.070061,0.065857,0.078468,0.071462,0.054180,0.044372,0.054647,0.050911,0.042971,...,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.070061,0.065857,0.078468,0.071462,0.054180,0.044372,0.054647,0.050911,0.042971,0.050911,...,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.065857,0.078468,0.071462,0.054180,0.044372,0.054647,0.050911,0.042971,0.050911,0.047641,...,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.078468,0.071462,0.054180,0.044372,0.054647,0.050911,0.042971,0.050911,0.047641,0.044839,...,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

### Dataset inspection:

In [11]:
df.shape

(1261, 1728)

In [12]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727
count,1261.000000,1261.000000,1261.000000,1261.000000,1261.000000,1261.000000,1261.000000,1261.000000,1261.000000,1261.000000,...,1261.000000,1261.0,1261.0,1261.0,1261.0,1261.0,1261.0,1261.0,1261.0,1261.0
mean,0.246619,0.246590,0.246570,0.246579,0.246604,0.246659,0.246749,0.246903,0.247074,0.247325,...,0.041237,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
std,0.126502,0.126540,0.126566,0.126555,0.126522,0.126464,0.126379,0.126263,0.126134,0.126066,...,0.198917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.014479,0.014479,0.014479,0.014479,0.014479,0.014479,0.014479,0.014479,0.014479,0.014479,...,0.000000,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
25%,0.136852,0.136852,0.136852,0.136852,0.136852,0.138253,0.138253,0.138253,0.139187,0.139187,...,0.000000,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
50%,0.299860,0.299860,0.299860,0.299860,0.299860,0.299860,0.299860,0.299860,0.299860,0.300327,...,0.000000,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
75%,0.347968,0.347968,0.347968,0.347968,0.347968,0.347968,0.347968,0.347968,0.347968,0.347968,...,0.000000,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
max,0.480149,0.480149,0.480149,0.480149,0.480149,0.480149,0.480149,0.480149,0.480149,0.480149,...,1.000000,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0